from enum import Enum

class FileName(str, Enum):
    ACSELX = "usuarios_acselx"
    ADDACTIS = "usuarios_addactis"
    BILLING_CENTER = "usuarios_billing_center"
    BOTMAKER = "usuarios_botmaker"
    CGWEB = "usuarios_cgweb"
    CLAIM_CENTER = "usuarios_claim_center" 
    CONTACT_MANAGER = "usuarios_contact_manager" 
    CRM = "usuarios_crm" 
    DATALAKE = "usuarios_datalake" 
    EAS = "usuarios_eas" 
    EXACTUS = "usuarios_exactus"
    EXACTUS_PERFILES = "usuarios_perfiles_exactus"
    MONOKERA = "usuarios_monokera"
    ONBASE = "usuarios_onbase"
    PMS = "usuarios_pms"
    POLICYCENTER = "usuarios_policycenter"
    PROPHET = "usuarios_prophet"
    QUALYS = "usuarios_qualys"
    SALESFORCE = "usuarios_salesforce"
    SEGCEN = "usuarios_segcen"
    SINIESTROS_WEB = "usuarios_siniestros_web"
    SOX_VIDA = "usuarios_sox_vida"
    AD_VIDA = "ad_vida"
    AD_PPS = "ad_pps"
    DNI_VS_USUARIOS = "dni_vs_usuarios"
    ENTRA_ID = "entra_id"
    ACTIVOS_GDH = "activos_gdh"
    CESADOS_GDH = "cesados_gdh"
    TICKETS_CESES = "tickets_ceses"
    DB_GENERALES = "db_generales"
    DB_VIDA = "db_vida"
    MATRIZ_ROLES = "matriz_roles"
    SSA = "usuarios_ssa"
    APP_LOGIN = "app_login"

    #genericos
    USUARIOS_AUTORIZADOS = "usuarios_autorizados"
    EPPS_AE = "epps_ae"
    EPPS_AC = "epps_ac"
    IGWPRD_AC = "igwprd_ac"
    IGWPRD_AE = "igwprd_ae"

