from enum import Enum

extension_file = ".csv"
class FileName(str, Enum):

    ACSELX = f"usuarios_acselx{extension_file}"
    ADDACTIS = f"usuarios_addactis{extension_file}"
    BILLING_CENTER = f"usuarios_billing_center{extension_file}"
    BOTMAKER = f"usuarios_botmaker{extension_file}"
    CGWEB = f"usuarios_cgweb{extension_file}"
    CLAIM_CENTER = f"usuarios_claim_center{extension_file}"
    CONTACT_MANAGER = f"usuarios_contact_manager{extension_file}"
    CRM = f"usuarios_crm{extension_file}"
    DATALAKE = f"usuarios_datalake{extension_file}"
    EAS = f"usuarios_eas{extension_file}"
    EXACTUS = f"usuarios_exactus{extension_file}"
    EXACTUS_PERFILES = f"usuarios_perfiles_exactus{extension_file}"
    MONOKERA = f"usuarios_monokera{extension_file}"
    ONBASE = f"usuarios_onbase{extension_file}"
    PMS = f"usuarios_pms{extension_file}"
    POLICYCENTER = f"usuarios_policycenter{extension_file}"
    PROPHET = f"usuarios_prophet{extension_file}"
    QUALYS = f"usuarios_qualys{extension_file}"
    SALESFORCE = f"usuarios_salesforce{extension_file}"
    SEGCEN = f"usuarios_segcen{extension_file}"
    SINIESTROS_WEB = f"usuarios_siniestros_web{extension_file}"
    SOX_VIDA = f"usuarios_sox_vida{extension_file}"
    AD_CONSOLIDADO = f"ad_consolidado{extension_file}"
    DNI_VS_USUARIOS = f"dni_vs_usuarios{extension_file}"
    ENTRA_ID = f"entra_id{extension_file}"
    ACTIVOS_GDH = f"activos_gdh{extension_file}"
    CESADOS_GDH = f"cesados_gdh{extension_file}"
    TICKETS_CESES = f"tickets_ceses{extension_file}"
    DB_GENERALES = f"db_generales{extension_file}"
    DB_VIDA = f"db_vida{extension_file}"
    MATRIZ_ROLES = f"matriz_roles{extension_file}"
    SSA = f"usuarios_ssa{extension_file}"
    APP_LOGIN = f"app_login{extension_file}"

    #genericos
    USUARIOS_AUTORIZADOS = f"usuarios_autorizados{extension_file}"
    EPPS_AE = f"epps_ae{extension_file}"
    EPPS_AC = f"epps_ac{extension_file}"
    IGWPRD_AC = f"igwprd_ac{extension_file}"
    IGWPRD_AE = f"igwprd_ae{extension_file}"

    ROL_TICKET = f"rol_ticket{extension_file}"
